import type { Discovery } from "./types";

/**
 * Mock neighborhood feed for Morningside Heights.
 * Each record is already in the normalized Discovery shape that
 * NYC Open Data adapters and Tavily results should produce.
 */
export const DISCOVERIES: Discovery[] = [
  {
    id: "book-culture",
    name: "Book Culture on Broadway",
    category: "bookstore",
    source: "live-discovery",
    sourceDetail: "Live discovery · independent bookstores",
    lat: 40.80655,
    lng: -73.96515,
    address: "2915 Broadway, at 114th Street",
    hours: "Open daily, late. The other shop is at 536 West 112th.",
    summary: "The independent bookstore on the Broadway corner, with a children's room downstairs.",
    about: "Book Culture has kept an independent shop at this corner, and another in the old post office building on 112th. It is a meeting place as much as a store: new fiction, cookbooks, graphic novels, and a downstairs room of puzzles and picture books. Ask for something that is not on a syllabus.",
    tip: "The 112th Street shop is the quieter of the two if Broadway feels loud.",
    tags: ["books", "culture"],
    passportCategory: "bookstore",
  },
  {
    id: "greenmarket",
    name: "Columbia Greenmarket",
    category: "farmers-market",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · farmers markets",
    lat: 40.80725,
    lng: -73.96455,
    address: "Broadway between 114th and 116th Streets",
    hours: "Thursday and Sunday, 8am–4pm, year-round.",
    summary: "Hudson Valley farms take over the Broadway median twice a week.",
    about: "GrowNYC has run this market since 2001. Thursdays ride the campus rush; Sundays are when neighbors load up for the week. Look for the information tent if you want a recipe for whatever you don't recognize. The stands change with the season, which is the point.",
    tip: "Go Sunday if you want room to talk to a farmer. Go Thursday if you only have a gap between classes.",
    tags: ["food", "sustainability"],
    passportCategory: "farmers-market",
  },
  {
    id: "ford-hall",
    name: "Ford Hall Food Pantry",
    category: "food-donation",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · food assistance",
    lat: 40.80605,
    lng: -73.96735,
    address: "616 West 114th Street",
    hours: "Monday, Wednesday, and Thursday, 11am–2pm. Closed on major holidays.",
    summary: "Community Impact's neighborhood pantry: fresh food, dry goods, and a clothes closet.",
    about: "Coordinators and volunteers staff Ford Hall three middays a week. Fresh food and dry goods go to families, elders, and people without housing. The closet takes warm clothes and housewares. Call (212) 854-6310 before you bring a group, and don't invent a donation they didn't ask for — ask at the door what's eligible today.",
    tip: "The public door is the pantry. You do not need a campus ID to bring a donation.",
    tags: ["volunteering", "food", "sustainability"],
    passportCategory: "community-event",
  },
  {
    id: "hungarian",
    name: "Hungarian Pastry Shop",
    category: "cafe",
    source: "live-discovery",
    sourceDetail: "Live discovery · neighborhood cafés",
    lat: 40.80345,
    lng: -73.96155,
    address: "1030 Amsterdam Avenue",
    hours: "Mon–Fri 7:30am–8:30pm · Sat–Sun 8:30am–8:30pm.",
    summary: "Bottomless coffee, no Wi-Fi, and a wall of books written at these tables.",
    about: "Open since 1961, across from the cathedral close. The pastry case is the famous part. The real habit is the bottomless cup and the fact that nobody will hurry you, or offer a password for the internet, because there isn't one. Authors' wall on the left. Peacocks sometimes audible from the grounds.",
    tip: "Leave the laptop in your bag. That is the house style, not a suggestion from us.",
    tags: ["coffee", "food", "books", "culture"],
    passportCategory: "cafe",
  },
  {
    id: "hex",
    name: "Hex & Co. West",
    category: "gaming",
    source: "live-discovery",
    sourceDetail: "Live discovery · game nights and pop-ups",
    lat: 40.80635,
    lng: -73.96535,
    address: "2911 Broadway",
    hours: "Mon–Thu 8am–11pm · Fri–Sat 9am–midnight · Sun 9am–11pm.",
    summary: "A board-game café with more than a thousand games and tables that expect strangers.",
    about: "The flagship Hex & Co. is a full city block of shelves, coffee, and open play. Daytime is quiet enough to study. Evenings fill with Commander nights, Dungeons & Dragons, and people learning a game they did not bring. You can show up alone. The staff will teach a short one.",
    tip: "If you only have an hour, say so. They'll point you away from the three-hour boxes.",
    tags: ["gaming", "coffee", "technology"],
    passportCategory: "community-event",
  },
  {
    id: "nypl",
    name: "Morningside Heights Library",
    category: "library",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · NYPL locations",
    lat: 40.8057,
    lng: -73.9657,
    address: "2900 Broadway",
    hours: "Hours change by day. Check nypl.org before a special trip.",
    summary: "The public library branch for this stretch of Broadway.",
    about: "A card still works better than an algorithm here. Holds, staff picks, and a room that is not a campus library — anyone with a New York address can use it. It sits just south of the game café and the bookstore, which makes 113th a better block than people admit.",
    tip: "Ask what just came back. The returns cart is more interesting than the new-book wall.",
    tags: ["books", "technology"],
    passportCategory: "cultural",
  },
  {
    id: "alma-mater",
    name: "Alma Mater",
    category: "public-art",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · public art",
    lat: 40.80785,
    lng: -73.96215,
    address: "Low Plaza, Columbia University",
    hours: "Outdoors, on the steps. The plaza is open.",
    summary: "Daniel Chester French's seated figure on the Low steps, owl hidden in the robe.",
    about: "Cast in 1903, Alma Mater faces College Walk from the steps of Low Library. The small owl in the folds of the robe is the campus scavenger hunt that actually rewards looking. The inscription is worth reading once without a photo in the way. This is public sculpture that the neighborhood treats as furniture, which is a compliment.",
    tip: "Look for the owl in the robe before you look it up.",
    tags: ["art", "history", "culture"],
    passportCategory: "cultural",
  },
  {
    id: "peace-fountain",
    name: "Peace Fountain",
    category: "public-art",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · public art",
    lat: 40.80315,
    lng: -73.9627,
    address: "Cathedral grounds, 1047 Amsterdam Avenue",
    hours: "Grounds open during daylight.",
    summary: "Greg Wyatt's bronze: an archangel, nine giraffes, and animals made by schoolchildren.",
    about: "Installed in 1985 beside the Cathedral of St. John the Divine. The archangel and the giraffes get the postcard. The rim is better: small bronzes cast from sculptures by New York schoolchildren, and plaques for figures who are not all from the same tradition. The fountain is often dry. The sculpture is the visit.",
    tip: "Count the giraffes, then walk the rim until a plaque surprises you.",
    tags: ["art", "history", "culture"],
    passportCategory: "cultural",
  },
  {
    id: "cathedral",
    name: "Cathedral of St. John the Divine",
    category: "historic",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · cultural institutions",
    lat: 40.80385,
    lng: -73.96185,
    address: "1047 Amsterdam Avenue",
    hours: "Grounds open by day. Sanctuary hours are posted at the door.",
    summary: "One of the largest cathedrals in the world, still unfinished, with peacocks on the lawn.",
    about: "The stonework stops on purpose in places. That unfinished edge is the thing to find, more than a photo of the rose window. The close connects the Hungarian Pastry Shop, the Peace Fountain, and a flock of peacocks who do not care about your schedule. Step inside if the door is open. The scale only lands in person.",
    tip: "Find one unfinished edge before you leave. The peacocks are a bonus, not the assignment.",
    tags: ["history", "culture", "art"],
    passportCategory: "historic",
  },
  {
    id: "grants-tomb",
    name: "General Grant National Memorial",
    category: "historic",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · historic sites",
    lat: 40.81335,
    lng: -73.96315,
    address: "Riverside Drive at West 122nd Street",
    hours: "National Park Service site. Check nps.gov so you don't meet a locked door.",
    summary: "The memorial above the Hudson, ringed by mosaic benches made with the neighborhood.",
    about: "Grant's Tomb is the formal monument. The benches around it were built in the 1970s with neighborhood artists and residents, and they are the part that feels like this block rather than a capital. Read one inscription upstairs, then sit on a bench and notice the two kinds of making. Sakura Park and Riverside Church are the next two minutes north and south.",
    tip: "If the memorial is closed, the benches and the view are still the visit.",
    tags: ["history"],
    passportCategory: "historic",
  },
  {
    id: "morningside-park",
    name: "Morningside Park",
    category: "park",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · parks properties",
    lat: 40.8064,
    lng: -73.9584,
    address: "Morningside Avenue, from 110th to 123rd Street",
    hours: "Open daily.",
    summary: "Olmsted and Vaux's cliff, pond, and waterfall between the Heights and Harlem.",
    about: "The park is a drop, not a lawn. Morningside Drive is the overlook; the park itself is down the stairs, with a pond and a waterfall at the south end. It is the seam between Morningside Heights and Harlem, which means it is not a campus quad with trees. Use the staircases. The cliff edge is a view, not an entrance.",
    tip: "Enter by a staircase near 116th if you want the waterfall without a long loop.",
    tags: ["sustainability", "history"],
    passportCategory: null,
  },
  {
    id: "gatehouse",
    name: "Gatehouse Garden",
    category: "garden",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · GreenThumb community gardens",
    lat: 40.80955,
    lng: -73.9587,
    address: "1195 Amsterdam Avenue, between 118th and 119th",
    hours: "Apr 1–Oct 31: Sat & Sun 10am–2pm, Wed 3:30–5:30pm.",
    summary: "A GreenThumb garden with beds, compost, pollinators, and a small flock of chickens.",
    about: "NYC Parks GreenThumb garden on Amsterdam, built like a tiny food system: vegetables, native beds, compost, and chickens. Open hours are real hours. If the gate is locked, the board still tells you when people are there. It is one of the few places in the neighborhood where sustainability is a chore list, not a slogan.",
    tip: "Saturday morning is the easiest time to find someone who can talk about the compost.",
    tags: ["sustainability", "food", "volunteering"],
    passportCategory: "community-event",
  },
  {
    id: "roerich",
    name: "Nicholas Roerich Museum",
    category: "museum",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · cultural institutions",
    lat: 40.80245,
    lng: -73.9687,
    address: "319 West 107th Street",
    hours: "Free. Usually weekday and weekend afternoons — check the door.",
    summary: "A free townhouse museum of Himalayan paintings, small enough to talk to the person at the door.",
    about: "A brownstone on 107th, between Broadway and the river, given over to Nicholas Roerich's mountain paintings. Admission is free, which changes how long you stay. The rooms are domestic. Pick one canvas where the sky is doing more than the peaks and you'll remember the color longer than the label.",
    tip: "Go without a group. The scale of the house does not want a tour voice.",
    tags: ["art", "culture", "history"],
    passportCategory: "cultural",
  },
  {
    id: "miller",
    name: "Miller Theatre",
    category: "music",
    source: "live-discovery",
    sourceDetail: "Live discovery · concerts and workshops",
    lat: 40.80835,
    lng: -73.96355,
    address: "2960 Broadway, at 116th Street",
    hours: "Follows the concert calendar. Posters live in the lobby and on the Broadway side.",
    summary: "Columbia's contemporary-music hall. The program is usually stranger than a night of background listening.",
    about: "Miller sits on Broadway at the north edge of College Walk. The season leans contemporary: composers you have not heard, early music set next to new work, and composer portraits. You do not need to be in a music program to buy a ticket or to simply learn what is on this week. The poster is a legitimate visit if the lobby is dark.",
    tip: "Read the whole program note for one piece. That is enough for a first stop.",
    tags: ["music", "culture"],
    passportCategory: "cultural",
  },
  {
    id: "postcrypt",
    name: "Postcrypt Coffeehouse",
    category: "music",
    source: "live-discovery",
    sourceDetail: "Live discovery · campus gatherings",
    lat: 40.80755,
    lng: -73.96085,
    address: "St. Paul's Chapel, Columbia University",
    hours: "Friday and Saturday nights during the academic year. Free.",
    summary: "Student-run acoustic sets in the chapel basement, with coffee and no cover.",
    about: "Postcrypt is how this campus actually hangs out when it is not in a dining hall. The room is under St. Paul's. The bill is acoustic, the price is zero, and the people running it are students. If you arrive on a weeknight, the quest is just to find the next date and put it somewhere you will see it.",
    tip: "Cash is occasionally useful for the snack table even though the music is free.",
    tags: ["music", "coffee", "culture"],
    passportCategory: "community-event",
  },
  {
    id: "riverside-church",
    name: "Riverside Church",
    category: "culture",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · cultural institutions",
    lat: 40.81165,
    lng: -73.96325,
    address: "490 Riverside Drive",
    hours: "Sanctuary and tower hours vary. Public programs are posted at the doors.",
    summary: "A riverside tower, a carillon, and a long habit of treating Sunday as a civic gathering.",
    about: "The architecture is the easy part: a tower you can see from the river path. The harder and better part is the bulletin board — concerts, meals, meetings, and social-justice ministries that outlive any single semester. Walk up from campus along Claremont or the park. Sakura Park is the lawn at its feet.",
    tip: "Read one posted program before you decide the visit was only the tower.",
    tags: ["culture", "volunteering", "music", "history"],
    passportCategory: "cultural",
  },
  {
    id: "scholars-lion",
    name: "Scholar's Lion",
    category: "public-art",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · public art",
    lat: 40.80815,
    lng: -73.96345,
    address: "116th Street gate, Columbia University",
    hours: "Outdoors, beside the Broadway gate.",
    summary: "Greg Wyatt's lion at the 116th Street gate — not Alma Mater, and easier to walk up to.",
    about: "People say 'the lion' and mean two different sculptures. Alma Mater is French, on the steps, with an owl. The Scholar's Lion is Greg Wyatt, near the Broadway gate, and it rewards a slower look: the books, the posture, the plaque. It is the shortest art quest in the neighborhood and a good way to learn the campus has more than one bronze animal.",
    tip: "Stand so you can see both the lion and the gate. The plaque is part of the piece.",
    tags: ["art", "history"],
    passportCategory: "cultural",
  },
  {
    id: "max-caffe",
    name: "Max Caffé",
    category: "cafe",
    source: "live-discovery",
    sourceDetail: "Live discovery · neighborhood cafés",
    lat: 40.81085,
    lng: -73.95615,
    address: "1262 Amsterdam Avenue",
    hours: "Open daytime into the evening most days.",
    summary: "An independent café on Amsterdam near 122nd, a deliberate step away from the famous pastry shop.",
    about: "Max Caffé is where people go when the Hungarian is full, or when they want Amsterdam instead of the cathedral view. Students treat the tables like a living room. Order something small and stay long enough to notice who is a regular. It is the right counter-quest if your café stamp is already the famous one.",
    tip: "Sit in, even if you only buy a coffee. The takeaway line teaches you nothing.",
    tags: ["coffee", "food"],
    passportCategory: "cafe",
  },
  {
    id: "toms",
    name: "Tom's Restaurant",
    category: "food",
    source: "live-discovery",
    sourceDetail: "Live discovery · neighborhood kitchens",
    lat: 40.80515,
    lng: -73.96585,
    address: "2880 Broadway, at 112th Street",
    hours: "Opens early and runs through the evening.",
    summary: "The diner under the red sign at 112th and Broadway.",
    about: "The exterior is the one from the song and the television show. The interior is a diner that still feeds people before class: eggs, coffee, a counter if you are alone. Order something you would have ordered without the sign. The block south of here is the library, the bookstore, and the game café — a better sequence than the postcard.",
    tip: "The counter is the move when you are by yourself.",
    tags: ["food", "culture"],
    passportCategory: null,
  },
  {
    id: "riverside-park",
    name: "Riverside Park overlook",
    category: "park",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · parks properties",
    lat: 40.8094,
    lng: -73.9702,
    address: "Riverside Drive at West 116th Street",
    hours: "Open daily.",
    summary: "The Hudson overlook west of campus, with a path that runs north toward Grant's Tomb.",
    about: "Cross west from the Broadway gate and the neighborhood suddenly has a river. The overlook at 116th is the shortest version of that fact. Stay until you can separate three sounds that are not traffic. If you keep walking north you will meet Sakura Park, Riverside Church, and the memorial without ever needing a subway.",
    tip: "Go when you have twenty minutes and no errand. Errands ruin this one.",
    tags: ["sustainability", "history"],
    passportCategory: null,
  },
  {
    id: "purple-waves",
    name: "Purple Waves",
    category: "market",
    source: "live-discovery",
    sourceDetail: "Live discovery · pop-up markets",
    lat: 40.80065,
    lng: -73.9586,
    address: "285 West 110th Street",
    hours: "Daily, 11am–7pm.",
    summary: "A sustainability-minded market and café where the Heights meet Harlem and the Upper West Side.",
    about: "Purple Waves sits at Frederick Douglass Circle with regional makers, coffee, and a terrace. It is the south edge of this map on purpose: the neighborhood does not end at 110th, and a low-waste market is a different kind of community room than a campus café. Find one product from a maker you cannot already name.",
    tip: "Ask where one thing was grown or made. The answer is the visit.",
    tags: ["sustainability", "food", "coffee"],
    passportCategory: "community-event",
  },
  {
    id: "sakura",
    name: "Sakura Park",
    category: "park",
    source: "nyc-open-data",
    sourceDetail: "NYC Open Data · parks properties",
    lat: 40.81235,
    lng: -73.96215,
    address: "Riverside Drive at West 122nd Street",
    hours: "Open daily.",
    summary: "A lawn and cherry trees between Riverside Church and Grant's Tomb.",
    about: "Sakura Park is the quiet hinge at the north end of the neighborhood. The trees are the gift; the lawn is the use. Even out of bloom it is the right place to sit between the church tower and the memorial. Read one plaque about how the park got here before you treat it as a shortcut.",
    tip: "Out of season, the plaques do the work the blossoms would have done.",
    tags: ["culture", "history"],
    passportCategory: null,
  },
];
